/*
 * 文件：test.jd.framework.orm.entity.Demo.java
 * 日 期：Fri May 02 00:55:59 CST 2014
 */
package test.jd.framework.orm.entity;

import com.jd.framework.orm.annotation.Column;
import com.jd.framework.orm.annotation.Table;
import com.jd.framework.orm.entity.BaseEntity;
import com.jd.framework.orm.schema.SchemaColumn;
import com.jd.framework.orm.schema.SchemaInfo;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * 
 * this file is generated by the jdorm pojo tools.
 *
 * @author <a href="mailto:liubingsmile@gmail.com">liubing</a>
 * @version 1.0.0
 */
@Table(name = "demo")
public class DemoEntity extends BaseEntity implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	
	/**
	 * primary key field of id
	 * 
	 */
	
	private Integer id;
	/**  */
	
	private String name;
	
	public DemoEntity() {
		super();
	}

	/**
	 * @return the id 
	 */
	@Column(isKey=true,name="id",isNull=false,typeLength=11 )
	public Integer getId() {
		return this.id;
	}
	
	/**
	 * 
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the name 
	 */
	@Column(isKey=false,name="name",isNull=true,typeLength=45 )
	public String getName() {
		return this.name;
	}
	
	/**
	 * 
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object o) {
		if ((o == null) || !(o instanceof DemoEntity)) {
			return false;
		}
		DemoEntity other = (DemoEntity)o;
		if (null == this.id) {
			if (other.id != null)
				return false;
		} else if (!this.id.equals(other.id))
			return false;
		return true;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}
	

	/* (non-Javadoc)
	 * @see test.jd.framework.orm.entity.Demo#getSchemaInfo()
	 */
	@Override
	public SchemaInfo getSchemaInfo() {
	SchemaInfo schemaInfo=new SchemaInfo();
	schemaInfo.setTableClass(Demo.class);
	schemaInfo.setReadDataBase("test");
	schemaInfo.setWriteDataBase("test");
	schemaInfo.setTableName("demo");
	List<SchemaColumn> schemaColumns=new ArrayList<SchemaColumn>();
	SchemaColumn schemaColumn=new SchemaColumn();
	schemaColumn.setColumnName("id");
	schemaColumn.setFieldClass(java.lang.Integer.class);
	schemaColumn.setFieldName("id");
	schemaColumn.setFieldValue(id);
	schemaColumn.setIstransient(false);
	schemaColumn.setNullable(false);
	schemaColumn.setPrimaryKey(true);
	schemaColumn.setTypeName("Integer");
	schemaColumn.setTypeLength(11);
	schemaColumn.setTypeScale(0);
	schemaColumns.add(schemaColumn);
	schemaColumn=new SchemaColumn();
	schemaColumn.setColumnName("name");
	schemaColumn.setFieldClass(java.lang.String.class);
	schemaColumn.setFieldName("name");
	schemaColumn.setFieldValue(name);
	schemaColumn.setIstransient(false);
	schemaColumn.setNullable(true);
	schemaColumn.setPrimaryKey(false);
	schemaColumn.setTypeName("String");
	schemaColumn.setTypeLength(45);
	schemaColumn.setTypeScale(0);
	schemaColumns.add(schemaColumn);
	schemaInfo.setColumns(schemaColumns);
	return schemaInfo;
	}

	

	/* (non-Javadoc)
	 * @see test.jd.framework.orm.entity.Demo#toJsonObject()
	 */
	@Override
	public String toJsonObject() {
	return "{'id':'"+id+"','name':'"+name+"'}";
	}
}